#!/bin/bash
read -p "输入用户名: " username
read -p "输入密码: " password

login_url="http://10.0.0.55/cgi-bin/do_login"
rs=`curl -sd "username=$username&password=$password&drop=0&trype=1&n=100" $login_url`

if [[ "$rs" =~ ^[0-9]+$ ]]; then
  echo "成功登陆"
  echo -n $rs > ~/.bit_network
  exit
fi

case $rs in
  user_tab_error)
    echo "认证程序未启动"
    ;;  
  username_error)
    echo "用户名错误"
    ;;  
  non_auth_error)
    echo "您无须认证，可直接上网"
    ;;  
  password_error)
    echo "密码错误"
    ;;  
  status_error)
    echo "用户已欠费，请尽快充值。"
    ;;  
  available_error)
    echo "用户已禁用"
    ;;  
  ip_exist_error)
    echo "您的IP尚未下线，请等待2分钟再试。"
    ;;  
  usernum_error)
    echo "用户数已达上限"
    ;;  
  online_num_error)
    echo "该帐号的登录人数已超过限额\n如果怀疑帐号被盗用，请联系管理员。"
    ;; 
  mode_error)
    echo "系统已禁止WEB方式登录，请使用客户端"
    ;;  
  time_policy_error)
    echo "当前时段不允许连接"
    ;;  
  flux_error)
    echo "您的流量已超支"
    ;;  
  minutes_error)
    echo "您的时长已超支"
    ;;  
  ip_error)
    echo "您的IP地址不合法"
    ;;  
  mac_error)
    echo "您的MAC地址不合法"
    ;;  
  sync_error)
    echo "您的资料已修改，正在等待同步，请2分钟后再试。"
    ;;  
  *)  
    echo "找不到认证服务器"
    ;; 
esac
